name: mikepro-first-django

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: flake8 . --ignore=E501

      - name: Test with pytest
        run: SECRET_KEY=django-insecure-sldkfjlsdkjflsdkjflskdjf pytest

  deploy:
    needs: tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mikepro-first-django"
          heroku_email: "mikepro@alfamail.ru"
          usedocker: true
