name: mikepro-first-django

on: [ push ]

jobs:                                                                      

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mikepro-first-django"
          heroku_email: "mikepro@alfamail.ru"
          usedocker: true
